{
	dataList: [
		{
			shopid: 1,
			shopname: "分类1",
			address: "地址1"
		}, {
			shopid: 2,
			shopname: "分类2",
			address: "地址2"
		}, {
			shopid: 3,
			shopname: "分类3",
			address: "地址3"
		}, {
			shopid: 4,
			shopname: "分类4",
			address: "地址4"
		}, {
			shopid: 5,
			shopname: "分类5",
			address: "地址5"
		}, {
			shopid: 6,
			shopname: "分类6",
			address: "地址6"
		}, {
			shopid: 7,
			shopname: "分类7",
			address: "地址7"
		}, {
			shopid: 8,
			shopname: "分类8",
			address: "地址8"
		}, {
			shopid: 9,
			shopname: "分类9",
			address: "地址9"
		}, {
			shopid: 10,
			shopname: "分类10",
			address: "地址10"
		}, {
			shopid: 11,
			shopname: "分类11",
			address: "地址11"
		}, {
			shopid: 12,
			shopname: "分类12",
			address: "地址12"
		}, {
			shopid: 13,
			shopname: "分类13",
			address: "地址13"
		}, {
			shopid: 14,
			shopname: "分类14",
			address: "地址14"
		}, {
			shopid: 15,
			shopname: "分类15",
			address: "地址15"
		}, {
			shopid: 16,
			shopname: "分类16",
			address: "地址16"
		}, {
			shopid: 17,
			shopname: "分类17",
			address: "地址17"
		}, {
			shopid: 18,
			shopname: "分类18",
			address: "地址18"
		}
	],
	pageCount: 1,
	currentPage: 1
}